### ISSUE TITLE
设置的正确，只是把目标路径由master改成了main，就是不能同步

### ISSUE THREAD

**Issue by thisPunk** [MayoBlueSky/My-Actions#1]
帮我看看，什么情况，谢谢
https://github.com/thisPunk/auto_sign/runs/2636318793?check_suite_focus=true

**Comment by BlueSkyClouds** [comment]
仓库名变了

**Comment by BlueSkyClouds** [comment]
重新复制粘贴 同步脚本

**Comment by MayoBlueSky** [comment]
pat没有勾选workflow   勾选即可

**Comment by MayoBlueSky** [comment]
remote: Invalid username or password. 重新生成=_=  PAT错了 可能有空格这些

**Comment by thisPunk** [comment]
> pat没有插入workflow可以立即插入

我刚才确实没有点workflow选项，前面有点的也还是不行，我刚才又重新生成了一个PAT，还是不行
https://github.com/thisPunk/auto_sign/runs/2636507518?check_suite_focus=true

**Comment by thisPunk** [comment]
> > pat没有插入workflow可以立即插入
> 
> 我刚才确实没有点workflow选项，前面有点的也还是不行，我刚才又重新生成了一个PAT，还是不行
> https://github.com/thisPunk/auto_sign/runs/2636507518?check_suite_focus=true

**Comment by MayoBlueSky** [comment]
重新生成 可能有空格被你复制进去了 导致PAT错误

**Comment by thisPunk** [comment]
> 重新生成 可能有空格被你复制进去了 导致PAT错误
我的问题，确实粘贴了空格进去，直接点击github提供的复制按钮就可以了，我之前可能手动复制的，前面带有了空格，谢谢啦！
