### ISSUE TITLE
腾讯视频除了签到其他任务都无法完成

### ISSUE THREAD

**Issue by pwj0528** [MayoBlueSky/My-Actions#10]
腾讯视频会员下载任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员观看任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员赠送任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});

**Comment by BlueSkyClouds** [comment]
任务为手动完成 并非自动
