### ISSUE TITLE
bark推送失败Response code 414 (Request-URI Too Large)

### ISSUE THREAD

**Issue by LittleNightmare** [MayoBlueSky/My-Actions#13]
在用百度贴吧签到的时候出现的，可能是我贴吧签到有亿点点多？
```
百度贴吧: 部分签到成功, 百度知道: 重复
共签: 115/199, 本次成功: 0, 本次失败: 84
```
刚刚试了下哔咔，可以正常推送

**Comment by BlueSkyClouds** [comment]
可能消息过长 手动改一下https://github.com/MayoBlueSky/My-Actions/blob/master/function/tieba/tieba.js#L18

**Comment by LittleNightmare** [comment]
我改成10大部分就可以发送成功了，但还是有失败的，我检查了下，是不是bark的api需要更新了？我不会js，但我看他的[API](https://github.com/Finb/bark-server/blob/master/docs/API_V2.md#api-v2)的实例，似乎用的都是`headers={
                "Content-Type": "application/json; charset=utf-8",
            }`

**Comment by BlueSkyClouds** [comment]
失败的同一时间签到过多  减少并发 或 增大间隔时间
$.CFG_maxSignBars = 5 // 每次并发执行多少个任务
$.CFG_signWaitTime = 5000 // 每次并发间隔时间 (毫秒)

**Comment by LittleNightmare** [comment]
是bark的发送消息失败，使用的是bark默认的服务器。之前的修改，让每条贴吧消息都是414，变成了部分
