### ISSUE TITLE
天翼云盘签到抽奖失败报错

### ISSUE THREAD

**Issue by MYYG** [MayoBlueSky/My-Actions#14]
`共有 1 个账号，即将开始签到`
`Traceback (most recent call last):`
`  File "function/cloud189/checkin.py", line 136, in <module>`
  `  main()`
`  File "function/cloud189/checkin.py", line 18, in main`
 `   login(username, password)`
`  File "function/cloud189/checkin.py", line 100, in login`
 `   captchaToken = re.findall(r"captchaToken' value='(.+?)'", r.text)[0]`
`IndexError: list index out of range`
`账号：密码：`
`Error: Process completed with exit code 1.`

是我一个人的问题吗 哭

**Comment by BlueSkyClouds** [comment]
已修复

**Comment by jingdongpi** [comment]
> 已修复

请问，我今天运行还是报这个错误，是我的版本不对吗
共有 1 个账号，即将开始签到
Traceback (most recent call last):
  File "function/cloud189/checkin.py", line 136, in <module>
    main()
  File "function/cloud189/checkin.py", line 18, in main
    login(username, password)
  File "function/cloud189/checkin.py", line 100, in login
    captchaToken = re.findall(r"captchaToken' value='(.+?)'", r.text)[0]
IndexError: list index out of range
Error: Process completed with exit code 1.
