### ISSUE TITLE
小米运动 接口好像改了

### ISSUE THREAD

**Issue by mjyhj** [MayoBlueSky/My-Actions#15]
https://github.com/kangwenhang/xiaomisport

**Comment by BlueSkyClouds** [comment]
已更新

**Comment by mjyhj** [comment]
我已经注销号重新注册重新绑定，然后测试了，无效。
但是用52破解上的这个可以。
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1489938&highlight=%D0%A1%C3%D7
![1](https://user-images.githubusercontent.com/22577418/128642893-729a05c5-ea25-4069-b826-e9ef3f8cc994.png)

**Comment by BlueSkyClouds** [comment]
早上无效 得在中午或者下午提交才会生效
