### ISSUE TITLE
腾讯视频好像用不了了

### ISSUE THREAD

**Issue by MaoSource** [MayoBlueSky/My-Actions#19]
大佬，腾讯视频好像用不了了
![image](https://user-images.githubusercontent.com/56857029/145794914-fec50884-e19c-4e28-b71e-a8dd47d1b3f4.png)

**Comment by BlueSkyClouds** [comment]
二次签到失效而已   有时间我看看   因为之前二签失效过 不确定是否取消了

**Comment by MaoSource** [comment]
> 二次签到失效而已 有时间我看看 因为之前二签失效过 不确定是否取消了

二签已经取消了，下面的任务都没有完成啊

**Comment by BlueSkyClouds** [comment]
任务并不是自动完成 只是为了防止忘记领取 自动领取  需要手动完成

**Comment by MaoSource** [comment]
> 任务并不是自动完成 只是为了防止忘记领取 自动领取 需要手动完成

好的
