### ISSUE TITLE
再骚扰一下。。。腾讯二签和v2ex签到怎么没有了

### ISSUE THREAD

**Issue by thisPunk** [MayoBlueSky/My-Actions#2]
腾讯二签目前可以用，手动执行没问题，v2ex之前有的这次取消了吗

**Comment by MayoBlueSky** [comment]
v2ex蜜汁失效  腾讯2签之前不是失效了就暂时移除  目前可以了？

**Comment by thisPunk** [comment]
> v2ex蜜汁失效 腾讯2签之前不是失效了就暂时移除 目前可以了？

腾讯绝对可以用，之前有几天确实用不了，早就恢复了，http://v.qq.com/x/bu/mobile_checkin

**Comment by Phil2048** [comment]
求v2   15号还可以的 这两天突然没了 发现是fork的被禁了  大佬有什么群吗 或者通知讨论的地方

**Comment by BlueSkyClouds** [comment]
v2ex国内被墙了

**Comment by Phil2048** [comment]
> v2ex国内被墙了

我是挂着XXX看的 这个也不影响签到吧 麻烦大佬放出来吧
