### ISSUE TITLE
大佬  爱奇艺报错了  还修吗

### ISSUE THREAD

**Issue by fadeds** [MayoBlueSky/My-Actions#20]
![image](https://user-images.githubusercontent.com/27796945/149905652-ec7ec421-8b9c-46c0-ad7d-7158cb1e0a60.png)

**Comment by BlueSkyClouds** [comment]
看样子就换了返回值的格式  晚点修复

**Comment by BlueSkyClouds** [comment]
看样子是爱奇艺更新了新的签到页面导致的失效

**Comment by fadeds** [comment]
大佬咋样了

**Comment by BlueSkyClouds** [comment]
暂时恢复了网页版  手机端因为我签过了 暂时没办法获取

**Comment by BlueSkyClouds** [comment]
爱奇艺已恢复
