### ISSUE TITLE
爱奇艺签到方式是否还有效？

### ISSUE THREAD

**Issue by Hywfred** [MayoBlueSky/My-Actions#22]
你好，前两天爱奇艺cookie和百度bduss签到失败，应该是cookie到期了。昨天我更换了爱奇艺的cookie之后，手动触发，签到成功。但是今天签到又失败了，看信息是说用户信息失效。请问这种情况是不是不太正常。麻烦查看一下，谢谢！
https://github.com/Hywfred/check_in/runs/5265604524?check_suite_focus=true
https://github.com/Hywfred/check_in/actions/runs/1874410562

**Comment by BlueSkyClouds** [comment]
手动触发再试试 如果还是登录失败   请用无痕模式登录并获取cookie  登录之后别注销 注销会导致cookie失效

**Comment by Hywfred** [comment]
啊，昨天我登录之后退出了，那可能是因为这个原因。手动触发是成功的。多谢回复，明天我在观察一下。
