### ISSUE TITLE
同步源仓库总是失败

### ISSUE THREAD

**Issue by 792825013** [MayoBlueSky/My-Actions#25]
不知道为啥就这个失败，别的能运行

**Comment by 792825013** [comment]
天翼云盘能执行，但实际没签上

**Comment by BlueSkyClouds** [comment]
同步源仓库失败与我无关 githud全自动待处理 无法干涉 大概率构建失败  无视即可
天翼云盘建议看下log 我是正常的https://cloud.189.cn/web/main/growthRecord

**Comment by 792825013** [comment]
log里是没有增加的

**Comment by BlueSkyClouds** [comment]
那就不清楚了 我的一切正常==

**Comment by 792825013** [comment]
我填写了secrets，设置了账号
运行还是提示
Run user=''
共有 0 个账号，即将开始签到

**Comment by BlueSkyClouds** [comment]
注意符号以及换行符 或secrets值填写错误
