### ISSUE TITLE
This job was skipped

### ISSUE THREAD

**Issue by heiqingyu** [MayoBlueSky/My-Actions#30]
大佬，前几天开始就一直不执行什么情况？都是跳过了

**Comment by Hywfred** [comment]
我也遇到这种情况。看了下9.26号有一个commit。不知道跟这个有没有关系。

**Comment by 2804842913** [comment]
每月免费2000分钟，分钟用超了，10月自己重新action一下

**Comment by CCXXXI** [comment]
```
if: github.event.repository.owner.id ...
```
删掉这行

**Comment by BlueSkyClouds** [comment]
不理解为什么 之前都正常突然跳过了

**Comment by BlueSkyClouds** [comment]
同步最新的看还会不会跳过

**Comment by 2804842913** [comment]
![image](https://user-images.githubusercontent.com/79502189/193544609-f9fb5199-37aa-4cb4-b123-870e1863550d.png)

**Comment by BlueSkyClouds** [comment]
不建议直接删掉 删掉别人start也可以触发你的工作流

**Comment by BlueSkyClouds** [comment]
看样子修复了 close

**Comment by StoneForests** [comment]
> 看样子修复了 close

是不是添加了  || ! github.event.sender.id  后解决的？

**Comment by BlueSkyClouds** [comment]
是的
