### ISSUE TITLE
大佬，腾讯视频一直提示脚本待更新

### ISSUE THREAD

**Issue by hahashifeng** [MayoBlueSky/My-Actions#32]
🔔腾讯视频会员签到, 开始!

🔔undefined, 开始!
验证成功，执行主程序
腾讯视频会员签到：脚本待更新 ‼️‼️
QZOutputJson=({"msg":"csrf refuse","ret":-16});

后面的任务都做不了

**Comment by BlueSkyClouds** [comment]
应该已经修复了 重新同步
