### ISSUE TITLE
同步代码的时候出现错误，进去看报错提示这些

### ISSUE THREAD

**Issue by OranHub** [MayoBlueSky/My-Actions#4]
/usr/bin/docker run --name ghcrioreposyncgithubsyncv230_da9fe3 --label 8a33c1 --workdir /github/workspace --rm -e PAT -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_GITHUB_TOKEN -e INPUT_SYNC_TAGS -e GITHUB_TOKEN -e SYNC_TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/myiQiYi-Daily/myiQiYi-Daily":"/github/workspace" ghcr.io/repo-sync/github-sync:v2.3.0  "https://github.com/MayoBlueSky/My-Actions.git" "master:master"

**Comment by MayoBlueSky** [comment]
PAT 错误,请检查是否多复制粘贴一个空格等  重新生成使用github自带的复制粘贴即可

**Comment by MayoBlueSky** [comment]
remote: Invalid username or password.

**Comment by OranHub** [comment]
OK；

**Comment by X20221022** [comment]
> PAT 错误,请检查是否多复制粘贴一个空格等 重新生成使用github自带的复制粘贴即可
牛逼大神
